name: Flight Availability Monitor

on:
  # Allow manual triggering from Actions tab
  workflow_dispatch:

  # Triggered by external cron service (cron-job.org) every 5 minutes
  repository_dispatch:
    types: [check-flights]

jobs:
  check-flights:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push commits back to repo

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub token for authentication

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run flight check
      env:
        SEATS_API_KEY: ${{ secrets.SEATS_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python flights_availability_check.py

    - name: Commit timestamp file if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

        # Check if file exists and add it
        if [ -f last_daily_message.txt ]; then
          git add last_daily_message.txt

          # Only commit and push if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "Update daily message timestamp [skip ci]"
            git push
            echo "✅ Timestamp file committed and pushed"
          else
            echo "ℹ️ No changes to timestamp file"
          fi
        else
          echo "⚠️ Timestamp file not found"
        fi
